// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.grpc.examples.student.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.examples.student.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.grpc.examples.student.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<io.grpc.examples.student.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .io.grpc.examples.student.StudentResponse studentResponse = 1;</code>
   */
  io.grpc.examples.student.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .io.grpc.examples.student.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .io.grpc.examples.student.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends io.grpc.examples.student.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .io.grpc.examples.student.StudentResponse studentResponse = 1;</code>
   */
  io.grpc.examples.student.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
