// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.grpc.examples.student;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string city = 3;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string province = 4;</code>
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();
}
